### PR TITLE
log video v6

### PR DESCRIPTION
**Pull request by joostvanzwieten**
New version. Compared with #77 child processes are not closed and entering a `with`-block focusses the figure (only for `PyPlotVideo`!).

### CODE REVIEW

**Comment by joostvanzwieten** [comment]
Wait! There is a mistake.

**Comment by joostvanzwieten** [comment]
Done. Focussing figures for `PyPlot` objects is also necessary due to the change in `examples/cylinderflow`. I shamelessly rebased and force-pushed the fix to this branch.

**Comment by gertjanvanzwieten** [comment]
Works for me :) in fact for the purpose of discussion I think I start to favour keeping things in a single pull request. It's hard to search back otherwise and I don't see much value in seeing the old code anyhow. But that's another discussion.
Green light for merging then?

**Comment by joostvanzwieten** [comment]
Yes!

**Comment by gertjanvanzwieten** [comment]
Videos are go!

**Pull request merged**
